<a href="https://colab.research.google.com/github/shivendr7/ml/blob/main/FeatureEngineeringForDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#m(kg)=m(lb)×0.45359237
import os
import pandas as pd
df=pd.read_csv("https://data.heatonresearch.com/data/t81-558/auto-mpg.csv",na_values=['NA','?'])
df.insert(1,'weight_kg',(df['weight']*.45359237).astype(int))
df

mpg  weight_kg  cylinders  ...  year  origin                       name
0    18.0       1589          8  ...    70       1  chevrolet chevelle malibu
1    15.0       1675          8  ...    70       1          buick skylark 320
2    18.0       1558          8  ...    70       1         plymouth satellite
3    16.0       1557          8  ...    70       1              amc rebel sst
4    17.0       1564          8  ...    70       1                ford torino
..    ...        ...        ...  ...   ...     ...                        ...
393  27.0       1265          4  ...    82       1            ford mustang gl
394  44.0        966          4  ...    82       2                  vw pickup
395  32.0       1040          4  ...    82       1              dodge rampage
396  28.0       1190          4  ...    82       1                ford ranger
397  31.0       1233          4  ...    82       1                 chevy s-10

[398 rows x 10 columns]

In [ ]:
import tensorflow as tf
matrix1=tf.constant([[3.,3.]])
matrix2=tf.constant([[2.],[2.]])
product=tf.matmul(matrix1,matrix2)
print(product)
print(product.numpy())
print(float(product))

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)
[[12.]]
12.0


In [ ]:
import tensorflow as tf
x=tf.Variable([1.0,2.0])
a=tf.Variable([3.0,3.0])
sub=tf.subtract(x,a)
print(sub)
print(sub.numpy())

tf.Tensor([-2. -1.], shape=(2,), dtype=float32)
[-2. -1.]


In [ ]:
x.assign([4.0,6.0]) #changing values in variable
print(x.numpy())

[4. 6.]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

In [ ]:
df=pd.read_csv("https://data.heatonresearch.com/data/t81-558/auto-mpg.csv",na_values=['NA','?'])
cars=df['name']
#print(df.horsepower.median())
df['horsepower']=df['horsepower'].fillna(df['horsepower'].median())

#pandas to numpy
x=df[['cylinders','displacement','horsepower','weight','acceleration','year','origin']].values

y=df['mpg'].values #regression

print(x,x.shape[1],x.shape[0])

[[  8.  307.  130.  ...  12.   70.    1. ]
 [  8.  350.  165.  ...  11.5  70.    1. ]
 [  8.  318.  150.  ...  11.   70.    1. ]
 ...
 [  4.  135.   84.  ...  11.6  82.    1. ]
 [  4.  120.   79.  ...  18.6  82.    1. ]
 [  4.  119.   82.  ...  19.4  82.    1. ]] 7 398


In [ ]:
#NN
model=Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) #hidden 1
model.add(Dense(15, activation='relu')) #hidden 2
model.add(Dense(1)) #output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=0,epochs=100)

In [ ]:
result=model.predict(x)
print(result.shape,result.shape[0],result.shape[1])

print(result[:10])

(398, 1) 398 1
[[21.556221]
 [14.775004]
 [15.990094]
 [15.334012]
 [18.38503 ]
 [13.383064]
 [ 8.355928]
 [ 9.015114]
 [ 7.384372]
 [10.790929]]


In [ ]:
score=np.sqrt(metrics.mean_squared_error(result,y))
score

8.645305260101134

In [ ]:
for i in range(5):
  print(cars[i],y[i],'predicted result='+str(result[i]))

chevrolet chevelle malibu 18.0 predicted result=[21.556221]
buick skylark 320 15.0 predicted result=[14.775004]
plymouth satellite 18.0 predicted result=[15.990094]
amc rebel sst 16.0 predicted result=[15.334012]
ford torino 17.0 predicted result=[18.38503]


In [1]:
#iris classification
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping


In [2]:
df=pd.read_csv("https://data.heatonresearch.com/data/t81-558/iris.csv",na_values=['NA','?'])

x=df[['sepal_l','sepal_w','petal_l','petal_w']].values
dummies=pd.get_dummies(df['species'])
print(dummies)
species=dummies.columns
print('x=>',x.shape[1],x.shape[0])
y=dummies.values
#print('y=>',y)
dummies.columns



     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]
x=> 4 150


Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')

In [4]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,8])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[1],[2],[3]])
print(a.shape,b.shape,c.shape,d.shape)
print(c[1:])
print(y.shape[1])
a*b

(4,) (4,) (2, 3) (3, 1)
[[4 5 6]]
3


array([ 2,  8, 18, 32])

In [5]:
model=Sequential()
print(x.shape[1])
model.add(Dense(50,input_dim=x.shape[1],activation='relu')) #hidden
model.add(Dense(25,activation='relu')) #hidden 2
print(y.shape[1])
model.add(Dense(y.shape[1],activation='softmax')) #output

model.compile(loss='categorical_crossentropy',optimizer='adam')
model.fit(x,y,verbose=0,epochs=100)

4
3


In [7]:
np.set_printoptions(suppress=True)
#used to round up the values
#to turn off scientific notation

In [8]:
pred=model.predict(x)
pred[:10]

array([[0.9940017 , 0.00598287, 0.0000154 ],
       [0.9866303 , 0.01332838, 0.00004128],
       [0.9909232 , 0.0090426 , 0.00003413],
       [0.9866948 , 0.0132532 , 0.00005194],
       [0.99465114, 0.00533414, 0.00001476],
       [0.9954346 , 0.00455674, 0.00000861],
       [0.99223447, 0.0077341 , 0.00003149],
       [0.99235326, 0.00762558, 0.00002113],
       [0.9832187 , 0.01670092, 0.00008029],
       [0.9878664 , 0.01209767, 0.00003591]], dtype=float32)

In [9]:
print(y[:10])
predicted=np.argmax(pred,axis=1)
expected=np.argmax(y,axis=1)
print(expected,'\n',predicted)
#argmax finds index of max prediction for each row

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
print('class for',x[:1],'=',species[predicted[1]])
print(model.predict(x[:1]))
species[np.argmax(model.predict(x[:1]))]

class for [[5.1 3.5 1.4 0.2]] = Iris-setosa
[[0.9940017  0.00598287 0.0000154 ]]


'Iris-setosa'

In [16]:
from sklearn.metrics import accuracy_score
asc=accuracy_score(expected,predicted)
print(asc)

0.98


In [17]:
sample_flower = np.array( [[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")

[[0.00355842 0.40489268 0.59154886]]
Predict that [[5. 3. 4. 2.]] is: Iris-virginica


In [21]:
sample_flower = np.array( [[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]],\
        dtype=float)
pred = model.predict(sample_flower)
print(pred)
print(np.argmax(pred,axis=1),'this')
pred = np.argmax(pred,axis=1)
print(f"Predict that these two flowers {sample_flower} ")
print(f"are: {species[pred]}")

[[0.00355842 0.40489268 0.59154886]
 [0.98912126 0.01085195 0.00002681]]
[2 0] this
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] 
are: Index(['Iris-virginica', 'Iris-setosa'], dtype='object')
