<a href="https://colab.research.google.com/github/shivendr7/ml/blob/assignments/numpyTut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
ar=np.array([[3,56,7,275]],dtype=np.uint8)

In [10]:
print(ar.shape, ar.dtype)
ar[0,1],ar[0]

(1, 4) uint8


(56, array([ 3, 56,  7, 19], dtype=uint8))

In [11]:
ar[0,1]=25
ar

array([[ 3, 25,  7, 19]], dtype=uint8)

In [12]:
ar=np.array([[1,2,3],[4,5,6],[8,9,10]])
print(ar.shape, ar.dtype, ar.size)

(3, 3) int64 9


In [14]:
np.array((32,25,26)).dtype

dtype('int64')

In [16]:
np.array({1,2,3}).dtype, np.array({2})

(dtype('O'), array({2}, dtype=object))

In [21]:
z=np.zeros((2,5))
z, z.dtype, z.shape, z.size

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]), dtype('float64'), (2, 5), 10)

In [24]:
rng=np.arange(15)  # elements from 0 to n-1
rng, rng.dtype, rng.size, rng.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 dtype('int64'),
 15,
 (15,))

In [26]:
lsp= np.linspace(1, 5, 12)   # equal space distributed from 1 to 15 and into 12 parts
lsp, lsp.dtype

(array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
        2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
        4.63636364, 5.        ]), dtype('float64'))

In [27]:
lsp1= np.linspace(1,4,4) 
lsp1

array([1., 2., 3., 4.])

In [28]:
emp= np.empty((4, 6))  # empty array with random elements filled
emp

array([[4.65328443e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [29]:
id= np.identity(5)
id, id.shape, id.size, id.dtype

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]), (5, 5), 25, dtype('float64'))

In [31]:
ar=np.arange(99)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
ar2=ar.reshape(3, 33) # 3*33==99
ar2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
ar3=ar2.ravel()  # to create a 1D array
ar3, ar3.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]), (99,))

In [39]:
x=[[1,2,3], [4,5,6], [7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0), ar.sum(axis=1)

(array([12,  8,  9]), array([ 6, 15,  8]))

In [41]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [42]:
ar.ndim #no of dimensions

2

In [43]:
f=ar.flat
for i in f:
  print(i, end=" ")

1 2 3 4 5 6 7 1 0 

In [45]:
ar.dtype, ar.nbytes #total bytes consumned 

(dtype('int64'), 72)

In [47]:
o= np.array([1,3,6,4,625,2])
o.argmax(), o.argmin(), o.argsort()
# indx of max, indx of min, indx of elements in sorted array

(4, 0, array([0, 5, 1, 3, 2, 4]))

In [49]:
print(ar)
ar.argmin()  #indx of min element in 1D array same size

[[1 2 3]
 [4 5 6]
 [7 1 0]]


8

In [50]:
ar.argmax(axis=0)

array([2, 1, 1])

In [52]:
ar2= np.array([[1,2,1], [4,0,6], [8,1,0]])
print(ar,'\n',ar2)
ar+ar2

[[1 2 3]
 [4 5 6]
 [7 1 0]] 
 [[1 2 1]
 [4 0 6]
 [8 1 0]]


array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [53]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [54]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [55]:
np.count_nonzero(ar) #no. of elements no equal to zero


8

In [56]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))