<a href="https://colab.research.google.com/github/shivendr7/ml/blob/GANs/UpsamplingVSDeconvolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

link-https://machinelearningmastery.com/upsampling-and-transpose-convolution-layers-for-generative-adversarial-networks/


In [1]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

In [2]:
# upsampling2D
X=asarray([[1,2],
           [3,4]])
print(X)
X=X.reshape((1,2,2,1))
model=Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))
model.summary()
yhat=model.predict(X)
Y=yhat.reshape(4,4)
Y

[[1 2]
 [3 4]]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d (UpSampling2D) (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [3., 3., 4., 4.],
       [3., 3., 4., 4.]], dtype=float32)

In [6]:
#doubling width tripling height
model2=Sequential()
model2.add(UpSampling2D(size=(2,3), input_shape=(2,2,1)))
model2.summary()
Y_n=model2.predict(X)
Y_n.shape

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_4 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


(1, 4, 6, 1)

Simple generator

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape, UpSampling2D, Conv2D

In [8]:
model=Sequential()
model.add(Dense(128*5*5, input_dim=100))
model.add(Reshape((5,5,128)))
model.add(UpSampling2D())
model.add(Conv2D(1,(3,3), padding='same'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_5 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


more about conv layer (1x1)- https://machinelearningmastery.com/introduction-to-1×1-convolutions-to-reduce-the-complexity-of-convolutional-neural-networks/

In [9]:
#upsampling with Conv2DTranspose
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose 

In [10]:
X=asarray([[1,2],
           [3,4]])
print(X)
X=X.reshape((1,2,2,1))

model=Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2,2,1)))
model.summary()

weights=[asarray([[[[1]]]]),asarray([0])]
model.set_weights(weights)

yhat=model.predict(X)
Y=yhat.reshape((4,4))
print(Y)

[[1 2]
 [3 4]]
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


Generator with Conv2DTranspose

In [11]:
from keras.models import Sequential
from keras.layers import Dense, Reshape, Conv2D, Conv2DTranspose

In [12]:
model=Sequential()
model.add(Dense(128*5*5, input_dim=100))
model.add(Reshape((5,5,128)))
model.add(Conv2DTranspose(1, (3,3), padding='same'))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 5, 5, 1)           1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


Conv2DTranspose = UpSampling2D + Conv2D